# Generated by Django 5.0.2 on 2024-04-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultradoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
